### PR TITLE
Sensitivity analysis

### LINKED ISSUE #146: SensitivityAnalysis WP6

### LINKED ISSUE #153: SensitivityAnalysis: `sensitivityCalculation` should return `SimulationResults` objects
The output of the `sensivitiyCalculation` function is now:

`return(list("tsData" = tsData, "pkData" = pkData))`

The size of `tsData` in the default example is 2.7 Mb, which is crazy! I think it is better to return the `SimulationResults` object that are returned by 

`  simResultsBatch <- unlist(runSimulationBatches(simBatch))`

`sensivitiyCalculation` should return a named list with two entries - `SimulationResults` and `pkData`.

`SimulationResults` should be a named list with entries for each varied parameter, with parameter path being the name of the entry (e.g. "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction")

the entries are basically what is generated by `simResultsBatch <- unlist(runSimulationBatches(simBatch))`. The names of `simResultsBatch` are by default the Ids of the runs, looks like

```
simResultsBatch
$`5d5c965e-833a-424b-8521-11328ae74acf`
SimulationResults: 
   Number of individuals: 1 

$`e73e9e66-aa47-4dab-b68c-e2d6be734874`
SimulationResults: 
   Number of individuals: 1 
```

the IDs should be replaced by the scale factor of the parameter that has been used for this run. In my version of the script, I have been keeping track of mapping of run IDs to parameter values by

```
    valuesIds <- lapply(parVarList, \(value){
      values <- defaultParamValues
      values[[param$path]] <- value
      simBatch$addRunValues(unlist(values, use.names = FALSE))
    })
    names(valuesIds) <- parVarList
```

So the end the output will contain all required information: all generated `SimulationResults` objects, sorted by parameter paths sorted by parameter scaling values. With object size probably less then 1 Mb because we are only storing references to .NET objects.

### LINKED ISSUE #154: SensitivityAnalysis: `sensitivityCalculation` should create an excel file only if specified by user
The function now always creates an excel file `PKdata.xlsx`. Instead, results should be saved in an excel file if the user specifies a path to the file (if the file with the specified name is already present, it will be overwritten). So additional argument `resultsFilePath = NULL`.

### LINKED ISSUE #155: SensitivityAnalysis: output of `sensitivityCalculation`
In the output excel file, following column names should be used:

For each calculated PK-parameter:
 - Name of the PK-parameter ( `C_max`)
 - <name>_Unit (`C_max_Unit`)
 - <name>_PercentChange (`C_max_PercentChange`)   (and not `C_max_PercentChangePK`)
 - <name>_Sensitivity (`C_max_Sensitivity`)  (and not `C_max_SensitivityPKParameter`)

### LINKED ISSUE #157: SensitivityAnalysis: calculation of pk parameter sensitivities
Sensitivities of PK-parameters (i.e. the values in the `<PKParameterName>_Sensitivity` column) should be done using the equation

image

where `PK_j` is the value of PK parameter calculated for the respective input parameter value `p_i`, `delta_p_i` is the value `p_i` minus the reference value of input parameter `p`, and `delta_PK_j` is the value of `PK_j` minus the reference value of PK parameter. E.g., senstivity of `C_max` at `ParameterFactor = 2` of parameter `Dose`
image

```
> (100-50) / (0.0005 - 0.00025) * (0.0005 / 100)
[1] 1
```

At least for `Dose`, sensitivity values for C_max are expected to be around 1 for all scale factor values.

### LINKED ISSUE #158: SensitivityAnalysis: Drop column `IndividualId` for the output `pkData`
`IndividualId` will always be 0, as population simulations are currently not supported by this function.

### LINKED ISSUE #159: `sensivitityTimeProfiles` should process get the output of `sensitivityCalculation`
No filtering or iterating should be required - all figures are directly generated by

```
sensitivityResults <- sensitivityCalculation(simulation, outputPaths, parameterPaths)
sensivitityTimeProfiles(sensitivityResults)
```

By default, they are directly created in the default output device (e.g. "Plots"-tab in R-Studio)

### LINKED ISSUE #160: `sensivitityTimeProfiles` and `sensitivitySpiderPlot` should save to png
Instead of using `savePlotList`

### LINKED ISSUE #161: `sensitivityTimeProfiles`: improve text size
It looks weird as many things do not fit in the figure

image

- The title
- Parameter paths (maybe multi-line?)
- Axis tics labels (e.g. the last 1500)

### LINKED ISSUE #163: sensitivityTimeProfiles: y axis log scaling
The argument for setting the scaling of the y axis is called `logConcentration`. However, not only concentrations could be plotted here (actually all kind of dimensions). The argument should be called smthg like "yAxisLog".

### LINKED ISSUE #165: sensitivitySpiderPlot: improve text size
Similar to time profiles, text is somehow huge.

### LINKED ISSUE #166: sensitivitySpiderPlot: weird behavior of the legend
When plotting directly to RStudio output, legend symbols are missing?

image

However, they are displayed when e.g. clicking on "zoom" or output to file.

### LINKED ISSUE #167: sensitivitySpiderPlot: allow setting scaling of x and y axis
lin/log.

### LINKED ISSUE #168: sensitivityCalculation fails if `pkParameters` is not supported.
```
> ls_results <- sensitivityCalculation(
+   simulation = simulation,
+   outputPaths = outputPaths,
+   parameterPaths = parameterPaths,
+   pkParameters = ""
+ )
Error in `mutate_cols()`:                                                                                                                                             
! Problem with `mutate()` column `rowid`.
i `rowid = paste0("OutputPath", seq(1:nrow(.)))`.
i `rowid` must be size 0 or 1, not 2.
Run `rlang::last_error()` to see where the error occurred.
```

or

```
> ls_results <- sensitivityCalculation(
+   simulation = simulation,
+   outputPaths = outputPaths,
+   parameterPaths = parameterPaths,
+   pkParameters = "olol"
+ )
Error in `mutate_cols()`:                                                                                                                                             
! Problem with `mutate()` column `rowid`.
i `rowid = paste0("OutputPath", seq(1:nrow(.)))`.
i `rowid` must be size 0 or 1, not 2.
```

### LINKED ISSUE #171: Test failures from `{ospsuite}` package updates
I am seeing build failures in #156, which are not due to the changes in that PR, but due to upstream changes in `{ospsuite}`. 

```r
-- Error (test-utilities-individual.R:29:3): It create IndividualCharacteristics with the correct values --
  Error: test_check: argument 'nullAllowed' is of type 'character', but expected 'logical'!
  Backtrace:
      x
   1. \-esqlabsR::readIndividualCharacteristicsFromXLS(...) at test-utilities-individual.R:29:2
   2.   \-ospsuite.utils::validateIsString(XLSpath, individualId)
   3.     \-ospsuite.utils::validateIsOfType(object, "character", nullAllowed)
   4.       \-ospsuite.utils::isOfType(object, type, nullAllowed)
```

### LINKED ISSUE #172: SensitivityCalculation should exit early if no output paths are specified
```
> # Empty path
> ls_results <- sensitivityCalculation(
+   simulation = simulation,
+   outputPaths = "",
+   parameterPaths = parameterPaths,
+   pkDataFilePath = "../Sensitivities.xlsx"
+ )
Error in `dplyr::mutate()`:                                                                                                                      
! Problem while computing `.rowid = paste0("OutputPath", seq(1:nrow(.)))`.
x `.rowid` must be size 0 or 1, not 2.
Run `rlang::last_error()` to see where the error occurred.
```

This should not fail (after running all sims) but rather check for empty paths at the beginning and throw an error if so.

### LINKED ISSUE #173: Sensitivity Analysis: issue a warning when a PK parameter is not found
Eg. here 

```
ls_results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  pkParameters = c("AUC_tEnd", "AUC_tEnd_norm", "C_min_norm"),
  pkDataFilePath = "../Sensitivities.xlsx"
)
```

`C_min_norm` is not available. It should continue but show a warning. Separater PR please.

### LINKED ISSUE #174: Sensitivity analysis when input parameter duplicated
```
ls_results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = c(parameterPaths, parameterPaths[[1]]),
  pkDataFilePath = "../Sensitivities.xlsx"
)

Error in names(simulationResultsBatch) <- parameterPaths : 
  'names' attribute [4] must be the same length as the vector [3]
```

Should `unique` on parameter paths before sim.

Next PR.

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
- [x] closes #174 
- [x] closes #173 
- [x] closes #172 
- [x] closes #171 
- [x] closes #168
- [x] closes #167
- [x] closes #166 
- [x] closes #165
- [x] closes #163
- [x] closes #161
- [x] closes #160
- [x] closes #159
- [x] closes #158
- [x] closes #157 
- [x] closes #155
- [x] closes #154
- [x] closes #153

Other tasks:
- [x] make sure none of the internal functions rely on `Parameter` objects, only parameter paths should be passed around
- [x] avoid using `.addRowid` function internally
- [x] have a single validation module for vector arguments of character type

Issues to fix in future PRs:
- #162
- #164

### CODE REVIEW

File: R/sensitivityCalculation.R [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+#' @param simulation An object of type `Simulation`.
+#' @param outputPaths Path (or a vector of paths) to the output(s) for which the
+#'   sensitivity will be analyzed.
+#' @param parameterPaths Path (a single or a vector) of the parameter(s) to be
+#'   varied.
+#' @param variationRange Optional numeric vector defining the scaling of the
+#'   parameters. The same variation range should be applied to all specified
+#'   parameters. If not specified, the following vector will be used: c(0.1,
+#'   0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 2, 3, 4, 5,  6, 7, 8, 9, 10).
+#' @param pkParameters A vector of names of PK parameters for which the
```
Comment (PavelBal) [inline R/sensitivityCalculation.R:13]: Add a hint that if `NULL`, all available PK-parameters are calculated.

**Comment by IndrajeetPatil** [comment]
The test is again failing for the same reason as was seen a while ago:

```r
Backtrace:
      x
   1. \-esqlabsR::readIndividualCharacteristicsFromXLS(...) at test-utilities-individual.R:29:2
   2.   \-ospsuite::createIndividualCharacteristics(...)
   3.     \-ospsuite::initPKSim()
   4.       \-rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce")
  
  [ FAIL 1 | WARN 9 | SKIP 0 | PASS 345 ]
```

This time it's surprising because I am using the latest nightly build of `ospsuite`.

**Comment by PavelBal** [comment]
> The test is again failing for the same reason as was seen a while ago:

Maybe not using the latest PK-Sim version?

**Comment by IndrajeetPatil** [comment]
> Maybe not using the latest PK-Sim version? 

This issue is resolved. 

The builds are now failing because of #171

File: R/sensitivityCalculation.R [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+
+  # set outputs to the provided path
+  clearOutputs(simulation)
+  addOutputs(outputPaths, simulation)
+
+  # save raw names of paths to create named list
+  parameterPathNames <- parameterPaths
+
+  # create simulation batch for efficient calculations
+  parameterPaths <- getAllParametersMatching(parameterPaths, simulation)
```
Comment (PavelBal) [inline R/sensitivityCalculation.R:64]: You are mixing parameter **paths** (which are strings) with **parameters**. Please name things accordingly.

When it's merged, we will re-write how results are generated. Now you have changed the code that separate `simulationBatch` is created for each parameter path, which is inefficient.

**Review by PavelBal — CHANGES_REQUESTED** [review]

**Comment by PavelBal** [comment]
Output to excel fails:

```
> simPath <- system.file("extdata", "Aciclovir.pkml", package = "esqlabsR")
> simulation <- loadSimulation(simPath)
> outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
> parameterPaths <- c(
+   "Aciclovir|Lipophilicity",
+   "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
+   "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
+ )
> ls_results <- sensitivityCalculation(
+   simulation = simulation,
+   outputPaths = outputPaths,
+   parameterPaths = parameterPaths,
+   pkDataFilePath = "../Sensitivities.xlsx"
+ )
Error in `dplyr::select()`:                                                                                                                                                            
! Can't subset columns that don't exist.
x Column `Parameter` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
```

File: R/sensitivityCalculation.R [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+  results <- list(
+    "SimulationResults" = batchResults,
+    "outputPaths" = outputPaths,
+    "parameterPaths" = parameterPaths,
+    "pkData" = pkData
+  )
+
+  # add additional attribute, which will be helpful for plotting methods to
+  # recognize this object
+  class(results) <- c("SensitivityAnalysis", class(results))
```
Comment (PavelBal) [inline R/sensitivityCalculation.R:108]: I am not sure what it does, but `ospsuite` already implements a R6 class `SensitivityAnalysis`. Could this be a problem?

Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R:108]: Oh?

Yes, this can create problems. I will rename it `SensitivityCalculation`.

Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R:108]: That way, there will also be consistency between the name of the function creating the object and the object itself.

File: R/sensitivityCalculation.R [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+  addOutputs(outputPaths, simulation)
+
+  # save raw names of paths to create named list
+  parameterPathNames <- parameterPaths
+
+  # create simulation batch for efficient calculations
+  parameterPaths <- getAllParametersMatching(parameterPaths, simulation)
+
+  # extract dataframes with results
+  batchResults <- purrr::map(
```
[the remark this answers is not in the document]
Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R:61]: It is not better _per se_. I am just trying to be internally consistent because I use `map2` in other place, and so I want to consistently use `map` family everywhere I am working with vectors.

As an aside, since _ospsuite_ has _purrr_ has a hard dependency, the _esqlabsR_ package also relies on _purrr_, so we are not gaining a new dependency. 

Here is a short summary of why I personally prefer `map` function family over `apply` function family.

Ref. https://r4ds.had.co.nz/iteration.html#base-r

image

File: R/sensitivityCalculation.R (hunk 2 above)
Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R]: The code now distinguishes between a R6 `Parameter` object and `parameterPath` string.

**Comment by IndrajeetPatil** [comment]
> Output to excel fails

File: R/sensitivityCalculation.R [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+    .x = parameterPaths,
+    .f = ~ .extractSimBatchResults(
+      simulation,
+      parameterPath = .x,
+      variationRange = variationRange
+    )
+  )
+
+  # name list with name of each parameter path
+  batchResults <- purrr::set_names(batchResults, parameterPathNames)
```
[the remark this answers is not in the document]
Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R]: `purrr::set_names()` has some stricter checks in place, but in this context, I guess we are unlikely to be surprised.

I have changed to use `names<-` function.

**Comment by PavelBal** [comment]
In general I am not against using third-party packages and their methods, but only if it has a benefit over base R (e.g. performance, better readability, less code...). However, I would prefer to use base R as long it is sufficient (e.g. `names(object)` instead of `purrr::set_names`). Excessive use of functions from packages make it hard to read the code for someone who is not familiar with packages. So if I have to learn new syntax, it must have some benefits.

File: R/sensitivityCalculation.R [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+  }
+
+  # remove the unneeded column
+  pkData <- dplyr::select(pkData, -c(".rowid"))
+
+  # final list with needed objects and dataframes for plotting functions
+  results <- list(
+    "SimulationResults" = batchResults,
+    "outputPaths" = outputPaths,
+    "parameterPaths" = parameterPaths,
```
[the remark this answers is not in the document]
Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R]: Okay, I will refactor functions to work with `parameterPaths` instead of a list of `Parameter` objects.

[the remark this answers is not in the document]
Comment (PavelBal) [reply R/sensitivityCalculation.R]: @IndrajeetPatil You are now returning `Parameter` objects and renamed the list entry to `parameters` - but we agreed on returning the paths?

[the remark this answers is not in the document]
Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R]: I haven't made that change yet. I will ask for your re-review once that change is made.

[the remark this answers is not in the document]
Comment (PavelBal) [reply R/sensitivityCalculation.R]: Ah ok sorry,  misunderstood the "I will" with "I have", sorry

**Comment by IndrajeetPatil** [comment]
@msevestre The builds are still [failing](https://ci.appveyor.com/project/StephanSchaller/esqlabsr/builds/42680334), even though I am using the latest version of _ospsuite_.

```r
Backtrace:
      x
   1. \-esqlabsR::readIndividualCharacteristicsFromXLS(...) at test-utilities-individual.R:29:2
   2.   \-ospsuite::createIndividualCharacteristics(...)
   3.     \-ospsuite::initPKSim()
   4.       \-rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce")
  
  [ FAIL 1 | WARN 11 | SKIP 0 | PASS 361 ]
```

File: R/sensitivityCalculation.R [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+                                   pkDataFilePath = NULL) {
+  # fail fast if specified PK parameters are not part of standard `enum`
+  validateIsIncluded(pkParameters, names(ospsuite::StandardPKParameter))
+
+  # set outputs to the provided path
+  clearOutputs(simulation)
+  addOutputs(outputPaths, simulation)
+
+  # create simulation batch for efficient calculations
+  parameters <- getAllParametersMatching(parameterPaths, simulation)
```
Comment (PavelBal) [inline R/sensitivityCalculation.R:55]: This is then not really needed here, because you can get the parameters in `.extractSimulationResultsBatch` from the paths... But you don't have to change it now, the whole "simulation" part has to be re-written anyways (separate PR then).

File: R/sensitivityCalculation.R [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+  # extract dataframe for PK parameters
+  pkData <- .simulationResultsBatchToPKDataFrame(simulationResultsBatch, parameterPaths)
+
+  # filter out unneeded PK parameters
+  if (!is.null(pkParameters)) {
+    pkData <- dplyr::filter(pkData, PKParameter %in% pkParameters)
+  }
+
+  # add a new `.rowid` column with unique name for each output path
+  pkData <- .addRowid(pkData)
```
Comment (PavelBal) [inline R/sensitivityCalculation.R:79]: This (and line 99) is only needed if writing to excel? Then it should be in the next if-condition. In general it feels somehow strange to add a new column to a (potentially very large) data frame just to split by sheets..

**Review by PavelBal — CHANGES_REQUESTED** [review]

**Comment by PavelBal** [comment]
https://github.com/esqLABS/esqlabsR/issues/172

File: R/sensitivityCalculation.R [hunk 9]
```diff
@@ -0,0 +1,131 @@
...
+  if (any(nchar(parameterPaths) == 0L)) {
+    stop("Path name in `parameterPaths` can't be an empty string.")
+  }
+
+  # validate PK parameters
+  validateIsCharacter(pkParameters)
+  if (any(nchar(pkParameters) == 0L)) {
+    stop("PK parameter name in `pkParameters` can't be an empty string.")
+  }
+  validateIsIncluded(pkParameters, names(ospsuite::StandardPKParameter))
```
Comment (PavelBal) [inline R/sensitivityCalculation.R:64]: Actually just realized - this should not be checked for. There are special use cases where the user can define a "user defined PK parameter" that would have a name that is not included in `ospsuite::StandardPKParameter`

**Review by PavelBal — CHANGES_REQUESTED** [review]

**Comment by PavelBal** [comment]
You sometimes pass parameter paths, sometimes parameter objects, getting parameter objects or their values at several places. E.g.

`  parameters <- getAllParametersMatching(parameterPaths, simulation)`
  in
`  sensitivityCalculation`
  
  
```
    parameters <- getAllParametersMatching(
    parameterPaths,
    purrr::pluck(simulationResultsBatch, 1L, 1L, "simulation")
  )
```
  in
`  .simulationResultsBatchToPKDataFrame`
  
```
    purrr::walk(
    .x = c(purrr::pluck(parameter, "value") * variationRange),
    .f = ~ simulationBatch$addRunValues(.x)
  )
```
  in
`  .extractSimulationResultsBatch`

then calculating the values again in `.addParameterColumns`. 

```
  data %>%
    dplyr::mutate(
      ParameterPath   = purrr::pluck(parameter, "path"),
      ParameterValue  = purrr::pluck(parameter, "value"),
      ParameterFactor = as.numeric(ParameterFactor)
    ) %>%
    dplyr::mutate(ParameterValue = ParameterValue * ParameterFactor)
```

Instead, this should be done once. I have the feeling you only need parameter paths, their initial values, and the ranges. Get the initial values at the beginning in `sensitivityCalculation` (and if it so convenient multiply them by factors) and then pass paths/values/factors across the functions, instead of repeating the same stuff.

File: R/utilities-sensitivity-Calculation.R [hunk 10]
```diff
@@ -0,0 +1,317 @@
...
+      names_from  = PKParameter,
+      values_from = c(PKParameterValue, Unit, PercentChangePK, SensitivityPKParameter),
+      names_glue  = "{PKParameter}_{.value}"
+    ) %>%
+    # columns that should not be included in the excel sheets
+    dplyr::select(-c(".rowid")) %>%
+    dplyr::rename_all(~ stringr::str_remove(.x, "_PKParameterValue")) %>%
+    dplyr::rename_all(~ stringr::str_remove(.x, "PK$|PKParameter$")) %>%
+    # all metrics for each parameter should live together
+    dplyr::select(
```
Comment (PavelBal) [inline R/utilities-sensitivity-Calculation.R:244]: Wohaaa whats this? nonono, we totally cannot hardcode that stuff!

File: R/sensivitityTimeProfiles.R [hunk 11]
```diff
@@ -0,0 +1,134 @@
...
+#'     results,
+#'     savePlots = TRUE,
+#'     units = "in",
+#'     height = 6,
+#'     width = 12
+#'   )
+#' }
+#'
+#' @export
+sensitivityTimeProfiles <- function(sensitivityCalculation,
```
Comment (PavelBal) [inline R/sensivitityTimeProfiles.R:44]: What's `units` here? Somehow I have no documentation for this function.

If these are the units for widht/height - it is better to rename the argument, as in the OSP context we usually think about units of the simulation output (µmol, h).

Comment (IndrajeetPatil) [reply R/sensivitityTimeProfiles.R:44]: No, it was units for plot dimensions. 
I have removed this argument. Height and width for saving plots should always be specified in inches now.

File: R/utilities-sensitivity-Calculation.R (hunk 10 above)
Comment (IndrajeetPatil) [reply R/utilities-sensitivity-Calculation.R:273]: This is to make sure two things when PK parameters data is saved to spreadsheet:

- the order in which columns corresponding to each PK parameter appear is the same no matter which PK parameters are asked for
- all columns corresponding to any single PK parameter are clubbed together (e.g., "C_max", "C_max_norm", "C_max_Unit"  "C_max_norm_Unit", "C_max_PercentChange", "C_max_norm_PercentChange"  "C_max_Sensitivity" "C_max_norm_Sensitivity" all appear next to each other rather than being dispersed)

``` r
library(esqlabsR)
library(ospsuite)
library(dplyr)

simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- c(
  "Aciclovir|Lipophilicity",
  "Applications|IV 250mg 10min|Application_1|ProtocolSchemaItem|Dose",
  "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
)

set.seed(123)
results <- sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths,
  variationRange = c(0.1, 2, 20),
  pkParameters = NULL
)
#> Following non-standard PK parameters will not be calculated:
#> 

pkDataWide <- results$pkData %>%
  esqlabsR:::.addRowid() %>%
  esqlabsR:::.convertToWide()

names(pkDataWide)
#>  [1] "OutputPath"                         "ParameterPath"                     
#>  [3] "ParameterFactor"                    "ParameterValue"                    
#>  [5] "C_max"                              "C_max_norm"                        
#>  [7] "C_max_Unit"                         "C_max_norm_Unit"                   
#>  [9] "C_max_PercentChange"                "C_max_norm_PercentChange"          
#> [11] "C_max_Sensitivity"                  "C_max_norm_Sensitivity"            
#> [13] "t_max"                              "t_max_Unit"                        
#> [15] "t_max_PercentChange"                "t_max_Sensitivity"                 
#> [17] "AUC_tEnd"                           "AUC_tEnd_norm"                     
#> [19] "AUC_tEnd_Unit"                      "AUC_tEnd_norm_Unit"                
#> [21] "AUC_tEnd_PercentChange"             "AUC_tEnd_norm_PercentChange"       
#> [23] "AUC_tEnd_Sensitivity"               "AUC_tEnd_norm_Sensitivity"         
#> [25] "AUC_inf"                            "AUC_inf_norm"                      
#> [27] "AUC_inf_Unit"                       "AUC_inf_norm_Unit"                 
#> [29] "AUC_inf_PercentChange"              "AUC_inf_norm_PercentChange"        
#> [31] "AUC_inf_Sensitivity"                "AUC_inf_norm_Sensitivity"          
#> [33] "CL"                                 "FractionAucLastToInf"              
#> [35] "CL_Unit"                            "FractionAucLastToInf_Unit"         
#> [37] "CL_PercentChange"                   "FractionAucLastToInf_PercentChange"
#> [39] "CL_Sensitivity"                     "FractionAucLastToInf_Sensitivity"  
#> [41] "MRT"                                "MRT_Unit"                          
#> [43] "MRT_PercentChange"                  "MRT_Sensitivity"                   
#> [45] "Thalf"                              "Thalf_Unit"                        
#> [47] "Thalf_PercentChange"                "Thalf_Sensitivity"                 
#> [49] "Vss"                                "Vss_Unit"                          
#> [51] "Vss_PercentChange"                  "Vss_Sensitivity"                   
#> [53] "Vd"                                 "Vd_Unit"                           
#> [55] "Vd_PercentChange"                   "Vd_Sensitivity"
```

<sup>Created on 2022-02-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

I will try to think of a way where this doesn't require hardcoding, but this is the best I can do for now.

Comment (IndrajeetPatil) [reply R/utilities-sensitivity-Calculation.R:273]: LOL, never mind. Figured out a way to do this without hardcoding. _dplyr_ is awesome. 🔥

File: R/sensitivityCalculation.R (hunk 8 above)
Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R]: I have removed the `.addRowid()` function, and there i no longer a new column is added only to be removed later.

File: R/sensitivityCalculation.R (hunk 9 above)
Comment (IndrajeetPatil) [reply R/sensitivityCalculation.R]: We don't check for this anymore.

File: R/utilities-sensitivity-Calculation.R [hunk 12]
```diff
@@ -0,0 +1,317 @@
...
+#'
+#' @note Note that the function will work only with a single parameter path.
+#'
+#' @keywords internal
+#' @noRd
+.extractSimulationResultsBatch <- function(simulation,
+                                           parameter,
+                                           variationRange) {
+  # check provided variation range using custom function
+  variationRange <- .validateVariationRange(variationRange)
```
[the remark this answers is not in the document]
Comment (IndrajeetPatil) [reply R/utilities-sensitivity-Calculation.R]: Yes, all argument validation happens now only once in `sensitivityCalculation()`.

**Comment by IndrajeetPatil** [comment]
@PavelBal Unless you have some other changes in mind, this PR is ready for a merge from my end.

**Comment by IndrajeetPatil** [comment]
I am wondering `variationRange` parameter should be renamed to `factorRange` parameter?

The corresponding dataframe column is called `ParameterFactor`, so it'd be nice to be internally consistent in how we are naming things.

**Comment by PavelBal** [comment]
`variationRange` is also how similar input is called in PK-Sim/MoBi https://docs.open-systems-pharmacology.org/shared-tools-and-example-workflows/sensitivity-analysis

So I would stick to the nomenclature.

File: R/sensitivityCalculation.R [hunk 13]
```diff
@@ -0,0 +1,127 @@
...
+#'   "Neighborhoods|Kidney_pls_Kidney_ur|Aciclovir|Glomerular Filtration-GFR|GFR fraction"
+#' )
+#'
+#' # extract the results into a list of dataframes
+#' sensitivityCalculation(
+#'   simulation = simulation,
+#'   outputPaths = outputPaths,
+#'   parameterPaths = parameterPaths
+#' )
+#' @export
```
Comment (PavelBal) [inline R/sensitivityCalculation.R:44]: Add @return to the doc.

**Review by PavelBal — APPROVED** [review]
