### PR TITLE
sensitivityTimeProfiles y label dimension fix

### LINKED ISSUE #823: `sensitivityTimeProfiles` axis labels not always correct in respect to dimension
When changing the unit of y axis to `ng/ml`, the label still says `Concentration (molar)`, though it should be `Concentration (mass)`.

```
p <- sensitivityTimeProfiles(results)
print(p)
```

Image

Changing units: 

`sensitivityTimeProfiles(results, yUnits = list("ng/ml"))`

Image

### PR DESCRIPTION
**Pull request by PavelBal**
- Fixes #823 

Fixed a bug when the dimension in the y-axis label of `sensitivityimeProfiles()` did not match the unit

### CODE REVIEW

File: R/sensivitity-time-profiles.R [hunk 1]
```diff
@@ -216,10 +216,12 @@ sensitivityTimeProfiles <- function(sensitivityCalculation,
       unique(data$xUnit), "]"
     )
   }
+  yUnitForPlot <- unique(data$yUnit)
+  yDimensionForPlot <- ospsuite::getDimensionForUnit(yUnitForPlot)
```
Comment (Felixmil) [inline R/sensivitity-time-profiles.R:220]: Is it possible that more than one result is returned here ? If yes, how to handle this ? We should at least add a [1] for now to make sure to print only the first element.

**Review by rengelke — APPROVED** [review]

File: R/sensivitity-time-profiles.R (hunk 1 above)
Comment (PavelBal) [reply R/sensivitity-time-profiles.R:220]: No this should never happen. `getDimensionForUnit()` always returns one value (or there is a bug).
