### PR TITLE
Fix plot title parsing

### LINKED ISSUE #471: Correctly read title of plotGrid
Following fields in Plots.xlsx should be split by `,`.

- Sheet `plotGrids`, title
- Sheet `exportConfiguration`, outputName

### PR DESCRIPTION
**Pull request by PavelBal**
Fixes #471

### CODE REVIEW

File: R/utilities-figures.R [hunk 1]
```diff
@@ -342,8 +342,9 @@ createPlotsFromExcel <- function(
   plotGrids <- apply(dfPlotGrids, 1, \(row) {
     plotGridConfiguration <- .createConfigurationFromRow(
       defaultConfiguration = defaultPlotGridConfig,
-      row[!(names(row) %in% c("name", "plotIDs"))]
+      row[!(names(row) %in% c("name", "plotIDs", "title"))]
```
Comment (PavelBal) [inline R/utilities-figures.R:345]: `title` column was processed as other columns, where we follow the logic that "list" of values are separated by a comma. In case of a title (and file name in the next changed code chunk), there is always only one value and should not be split.

**Comment by PavelBal** [comment]
@Felixmil I am merging now. Please review when you are back.
