### PR TITLE
Fix failing sensitivity-calculation after ospsuite update

### LINKED ISSUE #276: ospsuite update seems to have broken sensitivity analysis functionality
``` r
library(esqlabsR)

simPath <- system.file("extdata", "Aciclovir.pkml", package = "ospsuite")
simulation <- loadSimulation(simPath)
outputPaths <- "Organism|PeripheralVenousBlood|Aciclovir|Plasma (Peripheral Venous Blood)"
parameterPaths <- "Aciclovir|Lipophilicity"

sensitivityCalculation(
  simulation = simulation,
  outputPaths = outputPaths,
  parameterPaths = parameterPaths
)
#> Error in validateIsOfType(container, c("Simulation", "Container", "Molecule")): tryCatch: argument 'container' is of type 'NULL', but expected 'Simulation, or Container, or Molecule'!
```

<sup>Created on 2022-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

The error originates from here:

```r
> traceback()
17: stop(messages$errorWrongType(objectName, class(object)[1], objectTypes)) at validation-type.R#88
16: validateIsOfType(container, c("Simulation", "Container", "Molecule")) at utilities-entity.R#115
15: .getAllEntitiesMatching(paths, container, Parameter) at utilities-parameter.R#26
14: getAllParametersMatching(parameterPath, purrr::pluck(simulationResults, 
        1L, "simulation")) at utilities-sensitivity-calculation.R#150
13: .addParameterColumns(., simulationResults, parameterPath)
12: dplyr::group_by(., ParameterPath, PKParameter)
11: dplyr::group_modify(., .f = ~.computePercentChange(.))
10: dplyr::ungroup(.)
9: dplyr::select(., "OutputPath", dplyr::starts_with("Parameter"), 
       dplyr::starts_with("PK"), Unit, PercentChangePK, dplyr::everything(), 
       -c("IndividualId"))
8: dplyr::arrange(., ParameterPath, PKParameter, ParameterFactor)
7: purrr::map_dfr(.x = simulationResults, .f = ~pkAnalysesToDataFrame(calculatePKAnalyses(.x)), 
       .id = "ParameterFactor") %>% dplyr::rename(OutputPath = QuantityPath, 
       PKParameter = Parameter, PKParameterValue = Value) %>% .addParameterColumns(simulationResults, 
       parameterPath) %>% dplyr::group_by(ParameterPath, PKParameter) %>% 
       dplyr::group_modify(.f = ~.computePercentChange(.)) %>% dplyr::ungroup() %>% 
       dplyr::select("OutputPath", dplyr::starts_with("Parameter"), 
           dplyr::starts_with("PK"), Unit, PercentChangePK, dplyr::everything(), 
           -c("IndividualId")) %>% dplyr::arrange(ParameterPath, 
       PKParameter, ParameterFactor) at utilities-sensitivity-calculation.R#75
6: .simulationResultsToPKDataFrame(.x, .y)
5: .f(.x[[1L]], .y[[1L]], ...)
4: map2(.x, .y, .f, ...)
3: purrr::map2_dfr(.x = simulationResultsBatch, .y = parameterPaths, 
       .f = ~.simulationResultsToPKDataFrame(.x, .y)) at utilities-sensitivity-calculation.R#61
2: .simulationResultsBatchToPKDataFrame(simulationResultsBatch, 
       parameterPaths) at sensitivity-calculation.R#194
1: sensitivityCalculation(simulation = simulation, outputPaths = outputPaths, 
       parameterPaths = parameterPaths)
```

### PR DESCRIPTION
**Pull request by PavelBal**
Fixes #276

Unlist with named lists works differently than with unnamed list...

### CODE REVIEW

File: R/utilities-simulation.R [hunk 1]
```diff
@@ -25,7 +25,7 @@
 #' @param stopIfParameterNotFound Logical. If `TRUE` (default), an error is
 #'   thrown if any of the `additionalParams` does not exist. If `FALSE`,
 #'   non-existent parameters are  ignored.
-#'  @param simulationRunOptions Optional instance of a `SimulationRunOptions`
+#' @param simulationRunOptions Optional instance of a `SimulationRunOptions`
```
Comment (IndrajeetPatil) [inline R/utilities-simulation.R:28]: Can you please also update the `.Rd` file for this change?

**Review by IndrajeetPatil — CHANGES_REQUESTED** [review]

File: R/utilities-simulation.R (hunk 1 above)
Comment (PavelBal) [reply R/utilities-simulation.R:28]: Done

File: R/error-checks.R [hunk 2]
```diff
@@ -0,0 +1 @@
+
```
Comment (IndrajeetPatil) [inline R/error-checks.R:1]: I think `error-checks.R` can be deleted. It's an empty file anyway.

Comment (PavelBal) [reply R/error-checks.R:1]: Yes but let's keep it for the consistency with other osps packages. So in case we will require a check function we know where to put it :)

**Review by IndrajeetPatil — APPROVED** [review]
