### PR TITLE
- Remove empty rows when reading Scenarios

### LINKED ISSUE #400: Bug: `runScenarios` fails if there is an empty line between scenario definitions in the excel file

### PR DESCRIPTION
**Pull request by PavelBal**
- Check for duplicate names in scenarios

Fixes #400

### CODE REVIEW

File: R/utilities-scenario-configuration.R [hunk 1]
```diff
@@ -70,6 +70,9 @@ readScenarioConfigurationFromExcel <- function(scenarioNames = NULL, projectConf
     col_types = colTypes
   )
 
+  # Remove empty rows
+  wholeData <- wholeData[rowSums(is.na(wholeData)) != ncol(wholeData), ]
```
Comment (Felixmil) [inline R/utilities-scenario-configuration.R:74]: More explicitly: 
```suggestion
  wholeData <- dplyr::filter(wholeData, !dplyr::if_all(dplyr::everything(), is.na))
```

File: R/utilities-scenario-configuration.R [hunk 2]
```diff
@@ -89,6 +92,10 @@ readScenarioConfigurationFromExcel <- function(scenarioNames = NULL, projectConf
       stop(messages$scenarioConfigurationNameNotFoundWhenReading(scenarioName))
     }
     data <- wholeData[wholeData$Scenario_name == scenarioName, ]
+    # If multiple rows with the same scenario name if present, stop with an error
+    if (dim(data)[1] > 1) {
```
Comment (Felixmil) [inline R/utilities-scenario-configuration.R:96]: more explicitly:
```suggestion
    if (nrow(data) > 1) {
```

**Review by Felixmil — APPROVED** [review]
