### PR TITLE
Minor fixes

### LINKED ISSUE #836: Move `ospsuite.utils ` from Depends to Imports
To avoid requirement for validation (https://pharmar.org/white-paper/)

### LINKED ISSUE #860: Error if `plotGrids` sheet does not have a `title` column
If the `title` column is missing in the `plotGrid´ sheet of the Plots.xlsx` file, the code fails with the following message:

```
Error in if (!is.na(row$title)) { : argument is of length zero
3.
FUN(newX[, i], ...)
2.
plotGrids <- apply(dfPlotGrids, 1, \(row) {
plotGridConfiguration <- .createConfigurationFromRow(
defaultConfiguration = defaultPlotGridConfig,
row[!(names(row) %in% c("name", "plotIDs", "title"))] ... at utilities-figures.R#411
1.
createPlotsFromExcel(simulatedScenarios = simulatedScenarios,
observedData = observedData, projectConfiguration = projectConfiguration,
stopIfNotFound = TRUE, plotGridNames = list("Human_from_rat_IV",
"Human_from_rat_oral", "Human_from_beagle_IV", "Human_from_beagle_oral"))

```

Expected behavior - just don't use any title.

### LINKED ISSUE #863: Scenarios from Excel - Better validation when `SteadyState = TRUE` but the unit is not set
In the following case:

Image

creation of scenarios crashes with 

```
Error in if (stringr::str_detect(unit, pattern = mutants)) { : 
  missing value where TRUE/FALSE needed
5.
sourceUnit <- .encodeUnit(sourceUnit) at utilities-units.R#160
4.
toUnit(
quantityOrDimension = quantityOrDimension,
values = values,
targetUnit = baseUnit, ... at utilities-units.R#107
3.
scenarioConfiguration$steadyStateTime <- ospsuite::toBaseUnit(
quantityOrDimension = ospDimensions$Time,
values = ssTime,
unit = ssTimeUnit ... at utilities-scenario-configuration.R#147
2.
scenarioConfigurations <- readScenarioConfigurationFromExcel(
scenarioNames = scenarioNames,
projectConfiguration = projectConfiguration
) at r_GLUT4.R#15

```

Perform validation and show a meaningful error.

### PR DESCRIPTION
**Pull request by PavelBal**
Fixes #863 
Fixes #860 
Fixes #836

### CODE REVIEW

File: R/messages.R [hunk 1]
```diff
@@ -2,10 +2,9 @@ messages <- ospsuite.utils::messages
 
 # Parameters structure####
 messages$errorWrongXLSStructure <- function(
-  filePath,
-  expectedColNames,
-  optionalMessage = NULL
-) {
+    filePath,
```
Comment (PavelBal) [inline R/messages.R:5]: @Felixmil it looks like `styler` competes with Air here...

File: R/messages.R [hunk 2]
```diff
@@ -248,7 +241,15 @@ messages$stopScenarioMissingTimeUnit <- function(scenarioName) {
...
 messages$missingResultsForScenario <- function(scenarioName) {
   paste0(
-    "No simulation results could be computed for the cenario '",
+    "No simulation results could be computed for the scenario '",
+    scenarioName,
+    "'."
+  )
+}
+
+messages$missingSteadyStateTimeUnit <- function(scenarioName) {
```
Comment (PavelBal) [inline R/messages.R:250]: New error message for missing steady-state time unit

File: R/utilities-figures.R [hunk 3]
```diff
@@ -414,7 +416,8 @@ createPlotsFromExcel <- function(
       row[!(names(row) %in% c("name", "plotIDs", "title"))]
     )
 
-    if (!is.na(row$title)) {
+    # Ignore if title is not defined or no 'title' column is present
+    if (!is.na(row$title) || is.null(row$title)) {
```
Comment (PavelBal) [inline R/utilities-figures.R:420]: Fix for error when the 'title'  column is missing
